version: "3.7"

services:
  app:
    image: orldata:dev
    command: yarn run serve:dev
    build:
      target: development
    ports:
      - "4201:4200"
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        source: node_modules
        target: /usr/src/app/node_modules
      - type: volume
        source: lockfile
        target: /tmp
