GET https://data.cityoforlando.net/resource/ryhf-m453.json?$query=select processed_date, application_type where processed_date is not null order by processed_date DESC limit 30

Accept: application/json
X-App-Token: XsVdIPvgqvEmIgHOmFowjVeOu
